// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSCaptureExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSCaptureExtension.79650602-0048-438b-a465-d160c1989bd1";
        public const string Name = "VSCaptureExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "guillaume houchou";
        public const string Tags = "";
    }
}
